name: rickandmorty
description: A Rick And Morty Trivia app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.3+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  floor: ^1.4.2
  dio: ^4.0.6
  retrofit: ^3.0.0
  cached_network_image: ^3.0.1
  flutter_speed_dial: ^7.0.0
  beamer: ^0.12.3
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.0.1
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: GigaSans
      fonts:
        - asset: assets/fonts/GigaSansRegular.otf
        - asset: assets/fonts/GigaSansSemiBold.otf
          weight: 600
        - asset: assets/fonts/GigaSansBold.otf
          weight: 700
  
  assets:
    - assets/
    - assets/images/
